### ISSUE TITLE
Remove build-in layers from my projects

### ISSUE THREAD

**Issue by geniki** [webanno/webanno#1485] opened 2019-10-21 13:27 UTC
**Is your feature request related to a problem? Please describe.**
I need only my own custom annotations/layers in my projects. I'd like to export the layer schema and documents to IUMA CAS XMI, manipulate these using [cassis](https://github.com/dkpro/dkpro-cassis) and then import/reimport into WebAnno.

**Describe the solution you'd like**
I'd like to not have the build-in layers (Chunk, Coreference etc) anywhere - not in the UI when creating a new project and manually having to untick Enable and not in the XMIs that I export out of WebAnno (a seemingly related [bug](https://github.com/dkpro/dkpro-cassis/issues/70) in `cassis` because of their presence).

**Describe alternatives you've considered**
Having a script to go through the XMIs and remove the unneeded layers.

**Additional context**
None

**Comment by reckart** [comment] 2019-10-21 13:28
You can currently only uncheck the "enable" box for a layer. Deleting layers is not yet implemented.

Closing as duplicate of https://github.com/webanno/webanno/issues/1187

**Closed by reckart** 2019-10-21 13:28 UTC

**Comment by reckart** [comment] 2019-10-21 13:31
Also duplicate of https://github.com/webanno/webanno/issues/469

**Comment by geniki** [comment] 2019-10-21 14:07
Thanks @reckart. Apologies for the duplicate issue. I tried searching but didn't see them. Will follow  #469
