### ISSUE TITLE
Feedback panel blocks/hides project import button

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#148] opened 2015-10-27 16:23 UTC
On project settings page, if you end up having a content in feedback, the import button gets blocked/hidden by feedback panel.

Maybe needs padding or dynamic space.

![can t import project](https://cloud.githubusercontent.com/assets/1897100/10764689/99f7ea96-7ccf-11e5-8568-289fd7dfed20.png)

**Comment by reckart** [comment] 2015-11-30 13:48
Closing as duplicate of #161 which has more watches.

**Closed by reckart** 2015-11-30 13:48 UTC
Labels: bug, Settings, usability
