### ISSUE TITLE
Experimental import plain text has issues with windows line break

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#627] opened 2017-08-24 19:19 UTC
![image](https://user-images.githubusercontent.com/1056051/29684331-dea4517a-8911-11e7-93b4-bf03ce4a5176.png)
It occurs when a file with windows line break is uploaded

**Comment by reckart** [comment] 2017-08-24 19:38
Ehm... #447?

**Comment by reckart** [comment] 2017-08-24 19:39
Ah, this is for plain text files. It would be great if the report text could include relevant information.

**Comment by reckart** [comment] 2017-08-24 20:41
(note to myself: reading issue titles helps ;) )

**Comment by reckart** [comment] 2017-08-24 20:47
I have locally implemented a simple unit test that creates a text file with CRLF linebreaks and reads them using the experimental LineOrientedTextReader - but it doesn't provoke the error you describe.

Could you provide a stack trace?

**Comment by seyyaw** [comment] 2017-08-24 22:43
Below is a stack-trace.
`Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_121]
	at de.tudarmstadt.ukp.dkpro.core.tokit.BreakIteratorSegmenter.process(BreakIteratorSegmenter.java:63) ~[de.tudarmstadt.ukp.dkpro.core.tokit-asl-1.7.0.jar:?]
	at de.tudarmstadt.ukp.dkpro.core.api.segmentation.SegmenterBase.process(SegmenterBase.java:119) ~[de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl-1.7.0.jar:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.0.jar:2.10.0]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.0.jar:2.10.0]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:318) ~[uimaj-core-2.10.0.jar:2.10.0]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.10.0.jar:2.10.0]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:284) ~[uimaj-core-2.10.0.jar:2.10.0]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.importCasFromFile(ImportExportServiceImpl.java:376) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$FastClassBySpringCGLIB$$256f1e29.invoke(<generated>) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$EnhancerBySpringCGLIB$$6bc7e13e.importCasFromFile(<generated>) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at com.sun.proxy.$Proxy122.importCasFromFile(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.createInitialCas(DocumentServiceImpl.java:527) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.createInitialCas(DocumentServiceImpl.java:517) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.uploadSourceDocument(DocumentServiceImpl.java:471) ~[webanno-api-dao-3.3.0-SNAPSHOT.jar:?]
	... 198 more`

**Comment by reckart** [comment] 2017-08-25 06:25
I have tried including the BreakIteratorSegmenter and also tried several combinations of adding empty lines into my test file, but I still cannot reproduce. Could you please mail me the file that allows you to reproduce this issue?

**Comment by reckart** [comment] 2018-04-04 20:31
Closing as there was no further input.

**Closed by reckart** 2018-04-04 20:31 UTC
Labels: bug
