### ISSUE TITLE
Unable to change Layer while annotating, if the feature type is String (without tagset)

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#243] opened 2016-04-16 22:12 UTC
Steps to reproduce ( I did with a custom layer of type span which has stacking enabled by default)

1. Create a new layer of type `span` in a project.
2. Add a feature of type `uima.cas.String` to it with anyname, do not assign any tagset to it.
3. Open any document from the same project in Annotation.
4. Annotate on any existing annotation text. The details of annotation will be shown including feature.
5. Try to change the layer type by dropdown. It happens for Lemma as well in attached image.
![screenshot at 2016-04-17 00 04 01](https://cloud.githubusercontent.com/assets/1897100/14583909/bd3c5cf6-0430-11e6-92ac-80df24fc7d44.png)

**Expected**: User should be able to change layer type.

**Actual**: The dropdown is refreshed so fast because of the event (lost focus) that user can't change layer type from dropdown. The functionality of dropdown is broken in such cases.

---

ADEP = AnnotationDetailEditorPanel

| Focus before | Trigger | Action | Focus after |
| --- | --- | --- | --- |
| on input field in ADEP | TAB or SHIFT-TAB | Save and update ADEP | next field in ADEP; roll over to first field if focus was on last field |
| on input field in ADEP | ENTER | Save and update ADEP | remains on field (could be discussed to behave identical to TAB) |
| on input field in ADEP | click on field in ADEP | Save and update ADEP | focus goes to the clicked field |
| on input field in ADEP | click outside ADEP | Save and update ADEP | focus goes to wherever was clicked, if there is nothing to focus, then focus is cleared; this probably be left to the browser to handle |

**Comment by reckart** [comment] 2016-04-17 08:06
@aakashysharma which browser (+version) and which WebAnno version (string at bottom of screen)?

**Comment by aakashysharma** [comment] 2016-04-17 08:18
Apologies for missing that earlier. I'll keep that in mind when reporting future issues.

Webanno `3.0.0-SNAPSHOT (2016-04-16 23:51:53, build f0077abecf520048be7e59ec9bf82d920c12f114)`
Chrome `Version 49.0.2623.75 (64-bit)`  on linux-mint 17.3

**Comment by reckart** [comment] 2016-04-18 10:18
It should be possible to limit the AJAX refresh to the actual "Features" part of the annotation detail editor panel - if the "Actions" part is not updated on-focus-lost, then this should not be a problem.

Am I right that simply clicking on the dropdown a second time works? The second time, the focus should already be lost.

**Comment by reckart** [comment] 2016-04-18 10:29
@aakashysharma The problem is not specific to Chrome, right?

**Comment by aakashysharma** [comment] 2016-04-18 11:39
@reckart Theoretically I think it's not specific to Chrome. I can't test it for safari, I don't have a mac.

**Comment by aakashysharma** [comment] 2016-04-18 17:51
> Am I right that simply clicking on the dropdown a second time works? The second time, the focus should already be lost.

No. It resets back the focus to text-field in feature.

**Comment by reckart** [comment] 2016-04-18 18:45
@seyyaw It seems like WebAnno is always force-focussing an element in the annotation detail editor panel. I think this is ok in certain situations, e.g. directly after an annotation has been selected or created. But I think it should not simply happen on each AJAX refresh of the annotation detail editor area, in particular not if the reload was due to an auto-save on-focus-lost action. Do you have any comments on this?

**Comment by seyyaw** [comment] 2016-04-19 06:32
@reckart  I think once there was a request that the focus should always be there once the editor is open. I think, after auto save,better to keep the focus on the first text field. Otherwise, the user will always use the mouse to move the cursor back for modification. But after manual reload, we might not need it (even close the editor details). If you like, lets lose the focus  **on-focus-lost** and see if users complain.

**Comment by reckart** [comment] 2016-04-19 07:02
@seyyaw I think the auto-focus behavior makes a lot of sense in general. Prompted by this issue, however, it doesn't seem to make much sense indeed when the user explicitly tries moving the focus.

I just wonder if we can reliably detect on-focus-lost vs. any other actions causing an auto-save. Auto-change is presently triggered by "onblur" for dropdowns and by "onchange" for other components. We don't even explicitly handle "onfocuslost" atm ("onblur" seems to be the closest).

**Comment by seyyaw** [comment] 2016-04-29 13:17
If two text fields are present for a layer, it is not possible to to move the cursor to the second field. Is this issue related or should be its own @aakashysharma ?

**Comment by aakashysharma** [comment] 2016-04-29 13:18
@seyyaw  It's related because as soon as you try to move the cursor from first field to second, it refreshes! Cursor goes back to first again!

**Comment by reckart** [comment] 2016-04-29 15:12
This is a critical problem that needs to be fixed before the next (beta) release.

**Comment by aakashysharma** [comment] 2016-05-11 23:03
@reckart @seyyaw Please look at the commit and let me know if it breaks anything which existed earlier (if that's critical)

**Comment by seyyaw** [comment] 2016-05-12 06:09
Yes it breaks. 

1. The focus should be at the first text box for the first time (now it is not there and you have to do it manually)
2. Pressing TAB lost the focus in stead of moving to the next field

**Comment by reckart** [comment] 2016-05-12 14:17
The default focus should not be entirely disabled. It should only be disabled under certain cirumstances - or put otherwise - it should only be enabled under certain circumstances.

I think instead of trying to detect on-blur events, it may be easier to detect when the focus should actually be set - namely when a different annotation is selected by the user. I think this is the only case that requires setting the default focus, no? @seyyaw

**Comment by seyyaw** [comment] 2016-05-12 14:41
I am not sure what to mean by "**namely when a different annotation is selected by the user**".
But, I think we decide to have the focus on the first field when the user either select a text to annotate or  open existing annotation. Then, the focus should naturally proceed to the next field when the **TAB** or **ENTER** key is pressed and save and exit on the last field.

**Comment by reckart** [comment] 2016-05-12 14:43
I mean:

* the user creates a new annotation by marking a span of text or drawing an arc
* the user selects some annotation from the annotation view via a mouse click (or double-click I think actually)

In all other cases, the focus should not be changed.

**Comment by reckart** [comment] 2016-05-12 14:43
Sorry, update:

* the user creates a new annotation by marking a span of text or drawing an arc or doing any other action that creates a new annotation (e.g. pressing *ENTER* in auto-forward mode)
* the user selects some annotation from the annotation view via a mouse click (or double-click I think actually)

**Comment by seyyaw** [comment] 2016-05-12 14:46
What about moving from one field to the other (when we have multiple features per type)? Should the user do it manually or the TAB moves it to next field?

**Comment by reckart** [comment] 2016-05-12 14:48
In normal HTML forms, tab should always move the focus to the next field, no?

**Comment by reckart** [comment] 2016-05-12 14:52
* In non-autoforward mode, **ENTER** should just save the value, no moving of the focus, no additional action.
* In auto-foward mode, **ENTER** (and **SPACE**) should save and create the next annotation (and as part of creating the next annotation, the default focus should be set)
* In both modes, **TAB** should have the usual function of moving the focus to the next field. This is something that the browser should do by itself without any intervention from our side.

**Comment by seyyaw** [comment] 2016-05-12 14:56
And what happens when the **TAB** is pressed at the last field? The focus is lost, **ENTER** have no effect, annotation is not saved.

**Comment by reckart** [comment] 2016-05-12 15:03
After the last element - if I remember correctly - the browser should move the focus again to the first element. TAB-behavior can be controlled in HTML (cf. http://www.w3schools.com/tags/att_global_tabindex.asp) - I do not thing we need to handle that on the server side by forcing the focus anywhere.

**Comment by reckart** [comment] 2016-05-13 15:20
Discussed offline with @aakashysharma today: we have to reload the feature panel because changes to feature values may affect the constraints - if we do that, we loose the focus as well. So we probably really have to manage the focus on the server. There is a `getLastFocusedElementId()` on the AjaxRequestTarget class which may be useful for this.

**Comment by reckart** [comment] 2016-05-14 16:50
@aakashysharma I think we need to remove the DefaultFocusBehavior from the `populateItem` as you did it. The next easiest thing to fix is probably to set the focus on the first input in the ADEP **on annotation creation** and on **annotation selection**. I guess this would need to happen in the BratAnnotator class where the user actions are processed. We would still be loosing the focus on **ENTER** and on **TAB** due to the AJAX refresh, but at least we would be in a better situation then we are now.

**Comment by seyyaw** [comment] 2016-05-17 07:23
Great! Make sure the **Forward annotation** mode is not affected. For the **forward annotation**, the focus is always on the hidden text-field.

**Comment by seyyaw** [comment] 2016-06-27 16:59
I found it difficult to keep the cursor iterating through elements while the editor is refreshing itself. 
This what I can do
1. Get cursor on **first item**
2. On **Enter/TAB** save the annotation and move the cursor to the next element
3. But do **not reload the editor** so not sure how serious this is for constraint updates

**Comment by reckart** [comment] 2016-06-27 18:41
The editor needs to be refreshed basically on all annotation actions, otherwise the constraints effects to not kick in. Cf. #186 which your latest commit unfixed.

**Comment by aakashysharma** [comment] 2016-06-28 15:05
I've a solution which puts focus on first element when creating/reading annotation. So far, it works for me. Maybe it'll break some other functionality but I'm not sure about all test-cases to check that. 

Maybe @seyyaw & @reckart could check whether it breaks anything or maybe improve upon it.

**Comment by seyyaw** [comment] 2016-06-28 16:44
I do check the **TAB/ENTER** and **Forward annotation** and it works. I do not check constraints

**Comment by reckart** [comment] 2016-06-29 18:00
Ok... this one should be fixed now...

**Closed by reckart** 2016-06-29 18:00 UTC
Labels: Annotation, bug, usability
