### ISSUE TITLE
Layers are not exported if not set for any token

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#299] opened 2016-06-07 14:48 UTC
Layers imported in a document into WebAnno are not included upon export if they are not for any token. Although this is more compact, it's problematic if you need to know if the layer was in WebAnno (implying that it's set to _ for all tokens) or not (no information about this layer).

This is relevant in our workflow, where we merge the TSV data back into our original TEI document, but only for the layers that we originally exported. Currently we get around this by keeping a copy of the original TSV imported into WebAnno, but this is not ideal.

In case the current behaviour is seen as a feature and not a bug, maybe you could provide the user with a checkbox when exporting (something like "Include unset layers").

**Comment by seyyaw** [comment] 2016-06-07 14:57
This is not a bug, we export annotation so the layer included should have some annotation. May be we consider exporting all layers in future versions.

By the way, there is a separate layer and tagset export support in project settings page.

**Comment by cyplas** [comment] 2016-06-07 15:04
Yes, I understand. For (at least) our case though, this policy causes an ambiguity a la "null vs undef". A checkbox (which could be unchecked by default leading to current behaviour) during export would be great. :)

Thanks for the tip, we already use the handy layer and tagset export features so we can easily reuse the same layers or tagsets in multiple projects.

**Comment by reckart** [comment] 2016-06-07 15:56
@cyplas I don't think WebAnno makes a difference between null and undef. E.g. "null" and "<empty string>" are considered equivalent. If you want to make an explicit distinction for "undef", you should define a tag for it and assign it. Makes sense?

**Comment by cyplas** [comment] 2016-06-08 07:43
Sorry, I meant that not literally, but as an analogy to programming scenarios, rephrasing what I had explained before, i.e., that it's ambiguous when a layer is missing on export if it was already missing on import or merely had no annotations set for any token.

**Comment by reckart** [comment] 2016-06-08 07:56
The layers are configured in WebAnno - they are not reconstructed from the TSV header information. You cannot assume whether a layer is "present" or not by looking at the TSV because it contains incomplete information. The same goes for basically all of the other formats. When you do an XMI export, a typesystem file is also exported, but even that does not contain sufficient information for WebAnno to reconstruct layer configuration.

Even if WebAnno kept columns for all layers in the TSV, you would have no way of knowing whether the columns are empty because the annotator did explicitly decide not to create an annotation or because the annotator forgot it or maybe was never even asked to annotate on that layer. At present would need to keep such "workflow records" outside of WebAnno.

**Comment by cyplas** [comment] 2016-06-08 08:35
In our case, the TEI<->TSV conversion people work closely with the annotators, so we can distinguish the empty/forgot/unasked possibilities. But you're right that that's surely not true in general and perhaps our case is not common (I guess that's the question).

Still, wouldn't it be nice (especially since you've addressed #167) if it were reliably true that a TSV import into WebAnno immediately (that is, with no annotation changes) followed by a TSV export from WebAnno yielded an identical TSV file? :)

**Comment by seyyaw** [comment] 2016-06-08 08:48
We use the header in TSV import to check if the layer is already present in WebAnno. If the layer is not in WebAnno, no import possible. The export contain layer headers so it will be 1) easier for processing outside webanno easier (to know which column belongs to which layer...), and 3) to help the creation of layers while importing (an error displayed if an attempt is done to import the annotation before creating the layer). 

Adding an empty column for no annotation at all makes the file less readable.

If it is a strong requirement from the community, we opt to include an option (with check-box) in the next releases (at least not for WebAnno 3)

**Comment by cyplas** [comment] 2016-06-08 08:59
Yes, I agree that it would make the files less readable, so maybe it should only be done if there's enough demand.

**Comment by reckart** [comment] 2016-06-08 09:27
@cyplas the TSV format is a compromise that leans towards readability. But it is a compromise In particular, some things need to be observed (@seyyaw please comment if I forgot anything):

* offets are largely for informational purposes - the offsets on import may be different from the offsets on export because TSV reconstructs the text string from tokens/sentences
* IDs used in references may change depending on the number of columns
* the order of columns may change - it is always necessary to interpret the header
* the IDs of tokens (but not sub-token rows!) and of sentences remain stable

So an exported TSV may significantly differ from an imported TSV.

**Comment by cyplas** [comment] 2016-06-08 12:25
Although I don't understand all the details in your list, that's useful info that I might come back to, thank you.

**Closed** 2022-08-10 17:39 UTC
Labels: 🆕Enhancement, 🕶️UX, Module: TSV
