### ISSUE TITLE
Limiting display of contents of "Text" field in AnnotationDetailEditorPanel

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#500] opened 2017-05-25 16:57 UTC
When annotating a large block of text in a single span, such as text segmentation, it is required to display all the text in the "Text" field of the AnnotationDetailEditorPanel.
Maybe first n characters of display, followed by an ellipsis may suffice.

The tricky part is that if the block of the text contains several lines of text, ellipsis may only be applied on  a per-sentence basis, resulting in taking up more vertical space than it needs.

I think it is good to limit the content for cases like this.
I've seen  some weird behavior, where if a large block of span annotation happens, the DetailEditorPanel somehow takes up more than specified percentage of the width, making the actual document's width much shorter.

**Comment by kazukisan** [comment] 2017-05-30 18:43
It appears to me that the issue I encountered is more of a specific case, where all the characters within the span have no space. This metadata header kind of a document at the top of the plain text file, each field of the header is joined by ```|``` character, making it quite a long token. So, it appears that the text field in annotationdetaileditor is struggling to decide where the line break should be.

I will think of this a little more.

**Comment by kazukisan** [comment] 2017-06-01 16:42
That code diff above this comment is more of a hardcoded way with a specific number of "em" to cut off character displays with ellipsis, but it would be better if it is dynamically determined based on the current width of the annotation document panel (right hand side).

**Comment by reckart** [comment] 2017-06-01 20:07
That's more-or-less what I did in the "slots" section way back to avoid cases with too long text:

```
                                <tr wicket:id="slots">
                                    <td><span wicket:id="role"></span></td>
                                    <td><div class="hfill k-textbox"
                                        style="display: block; white-space: nowrap; background: 0; line-height: 2.13em; max-width: 20em; max-height: 2.13em; padding-left: 0.3em; padding-right: 0.3em; width: 100%; overflow:hidden; text-overflow: ellipsis;"
                                        wicket:id="label"></div></td>
                                </tr>
```

I had tried to figure out how to make this adapt automatically to the width of the box, but I did not find a solution - at least none without JavaScript.

For you first comments, I had the impression you were looking for a solution that would shorted the text on the server side and in a way that would preserve beginnings and ends of sentences if multiple sentences were selected, e.g.

```
This is ...<snip>... sentence 1.
This is ...<snip>... sentence 2.
This is ...<snip>... sentence 3.
```

`StringUtils.abbreviateMiddle(String, String, int)` would solve this server-side.

**Comment by kazukisan** [comment] 2017-06-01 20:31
Thanks for the comment, I appreciate it. I did observe the similar css properties after I applied it to the selectedText, but it is good to know that you were trying to find a solution there, too.

For the client side solution, the user preference setting of editor panel percentage needs to be exposed to the Javascript, and the current width of the left hand side (or perhaps right hand side editor panel, if the width is "before it got too wide") needs to be known. I can see how wicket IDs are assigned in the server side for these divs, but I wasn't sure how I could  do JQuery coding to use these wicket IDs, which end up being some kind of random integers in the client side. Overall, that's the idea I had.

I think dynamically assigning the "em" value would be more graceful, although 12 em or 20 em (as long as it is kept within reasonable width) would work ok, at least fixing the more severe issue.

**Comment by reckart** [comment] 2017-06-01 20:46
I think it is possible to set fixed IDs. I think you just have to set add `id='xxx'` in the HTML - it also should be possible to set the markup ID in the code (`setMarkupId(markupId)`). Or to override `onComponentTag()` of the Label which shows the selected text and manually set width there. I'm not really sure though how to convert the percentage sensibly into a max width. It might be an alternative to set the width of the detail panel to a fixed width, e.g. a fixed number of pixels.

**Comment by reckart** [comment] 2017-07-24 22:15
How about just limiting the height of the selected-text element and adding a scroll bar?

**Comment by reckart** [comment] 2017-07-24 22:17
As the sidebar width is configurable, it is a bit undesirable to limit the field to a certain width.

@kazukisan I'm resolving the issue assuming that the scrollbar resolves it. If you have a better idea, please re-open or create a new one.

**Comment by kazukisan** [comment] 2017-07-24 22:32
getting build failure with commit 2aff95346a7f4fa074cc6d29ad71cce16253de13, (I am not sure of the exact commit number), but if that's resolved, I would like to test this, and closing sounds fine to me for now.

**Comment by reckart** [comment] 2017-07-24 22:45
Build should be good again with commit 803a8c4.

**Comment by kazukisan** [comment] 2017-07-24 22:57
Thanks, and when I experimented, the behavior did change, but looks like I will need to create a new issue.
I am testing with a veerryyyyyyyyylooooooooooooongstriiiiiiiiiiiiiiiiiiiiiingWithoutAnyDelimiterAllOneeeeeeeeeeeeLineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee , and it looks like now the page itself expands very broadly, placing the DetailEditorPane to very very far right. Hmm.. I couldn't see a scroll bar in this case.

Yes, I agree that it is undesirable to limit the width of the text width, but as long as that width adjusts to the right side editor plane's size, it should be ok, I just haven't got around to this...

**Comment by reckart** [comment] 2017-07-25 06:38
Maybe `word-wrap: break-word` could also work.

**Comment by reckart** [comment] 2017-07-25 06:40
Btw. the layout on the annotation page is now flexbox. Possibly things that did not work before might work now.

**Comment by reckart** [comment] 2017-07-25 08:43
Reopening as there are a few additional ideas to test and a defined way to test them (i.e. using the `veerryyyyyyyyylooooooooooooongstriiiiiiiiiiiiiiiiiiiiiingWithoutAnyDelimiterAllOneeeeeeeeeeeeLineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`.

**Comment by reckart** [comment] 2017-07-25 08:44
Mind I just checked the page sources of this (yes, the one you look at) GH page and it seems to use `word-wrap: break-word` to ensure that `veerryyyyyyyyylooooooooooooongstriiiiiiiiiiiiiiiiiiiiiingWithoutAnyDelimiterAllOneeeeeeeeeeeeLineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` is wrapped instead of exploding the comment box ;)

**Comment by reckart** [comment] 2017-07-25 14:43
Actually for reproducing things, a project export is much more convenient.

**Comment by kazukisan** [comment] 2017-07-25 14:44
let me try that

**Comment by kazukisan** [comment] 2017-07-25 14:52
Here is the project export.

To reproduce,
1. You can set the layer to something like Chunk, maybe "Surface" layer would do too?
2. (I did set the font size to 100%, because somehow it is by default 120% now???)
3. Highlight the entire first line starting with ```|Head|```
4. Notice that EditorPanel takes up a lot of space like the screen shot above
5. Now click "Open" and choose the same document, and you should be able to see the behavior that looks like the 2nd screen shot from the comment above.

Hopefully the project export works out well!

[test_long_string_one_line_2017-07-25_1049.zip](https://github.com/webanno/webanno/files/1173733/test_long_string_one_line_2017-07-25_1049.zip)

**Comment by reckart** [comment] 2017-07-25 18:02
*wrt. font size* - I got some feedback that it is somewhat difficult to aim when making annotations. Since I suppose most use cases don't use the full real-estate of modern screens anyway, I increased the default font size a bit. Bad idea?

**Comment by kazukisan** [comment] 2017-07-25 18:13
I think this gets into a matter of preference, so I don't think I can provide constructive feedback.

Leaving at 100% by default (because 100% is a common number), but having this default configured by settings.properties also sounds fine to me. Isn't this already configurable by settings.properties?

**Comment by reckart** [comment] 2017-07-25 22:48
@kazukisan I think I found a pretty decent solution - check it out ;)

**Comment by kazukisan** [comment] 2017-07-25 22:52
Yes, working very well, and thank you for taking a look at this!

**Closed** 2017-07-25 22:56 UTC
Labels: Annotation, enhancement, feature-request, usability
