### ISSUE TITLE
Deleting a chain instance also deletes one of the span instances

### ISSUE THREAD

**Issue by mmev** [webanno/webanno#120] opened 2015-09-17 13:23 UTC
Is it intentional that deleting a chain instance also deletes one of the span instances the chain-arc is "attached to"?

Example on Experimental: CI = coreference annotation instance; no linked list behaviour
CI1 --(Coreference)-- CI2
If I activate the label of the arc, also one of the CI instances will be selected, and also deleted, if I just would like to delete the arc between them. I would not assume this behaviour.

Some details:
- The additionally activated CI instance is most of the time the first one, but not always. 
- Which CI will be activated is not depending on the "direction" of the chain-arc (which is actually undirected, but at creating time, I have a "source" and a "target" instance).
- Sometimes, an error with message "CasDoctor has detected problems and checks are fatal." will be thrown preventing the tool from deleting anything.

**Comment by reckart** [comment] 2015-09-17 13:25
There is a known glich in the display of the selection for arcs. If you select an arc, the highlight will be rendered on the span - but if you delete, it should actually remove only the arc, not the span - so there may be another glitch.

**Comment by reckart** [comment] 2015-09-17 13:26
If you see a "CasDoctor has detected problems and checks are fatal." message, please open an issue for it and describe how you have triggered this. This is related to the "mysteriously missing spans that are in XMI but not on screen" problem. If there is a stacktrace, please post it to the new issue as well.

**Comment by reckart** [comment] 2015-09-17 13:31
The "CasDoctor" is a safeguard doing extra sanity checks before saving a CAS. The cab be used to prevent saving if the CAS contains inconsistent information - and in the same way to detect actions that trigger bugs leading to an inconsistent CAS content.

**Comment by mmev** [comment] 2015-09-17 13:31
To your comment on "glich":
Instances of the relation type has not this problem.

To your comment on "CasDoctor":
- With chain type, it seemed to be not really deterministic... But no other error message was displayed.
- With relation type, it pretended me (=user) to delete a span instance with a relation arc to or from it - which is a really good feature!

**Comment by reckart** [comment] 2015-09-17 13:33
ref "glitch": "relation" layers are not affected indeed, only chains. Chains are quite different from relations.

**Comment by mmev** [comment] 2015-09-17 13:35
"Chains are quite different from relations." (by reckart)
What is the difference between a relation layer and a chain layer with linked list behaviour? -- Or what is the intended difference?

**Comment by reckart** [comment] 2015-09-17 13:45
For relations, you also need a span layer that the relation can attach to. Spans and relation are stored in separate features structures:

```
span1 (POS)  { begin: 10, end: 20 }
span2 (POS)  { begin: 30, end: 40 }
rel1 (Dep) { Gov: span1, Dep: span2, value: "subj"}
```

A chain consists of links that are spans and that point to the next link:

```
chainSpan1 { begin: 10, end: 20, referenceType: "entity", referenceRelation: "anaphoric", next: chainSpan2 }
chainSpan2 { begin: 10, end: 20, referenceType: "entity", referenceRelation: "anaphoric", next: null }
```

**Comment by mmev** [comment] 2015-09-17 13:52
Ok, thanks.
(chainSpan2 should maybe have begin:30 and end:40)

**Comment by reckart** [comment] 2015-09-17 13:52
Yes, I had updated that already 2-3 times for offsets and better formatting ;)

**Comment by reckart** [comment] 2015-09-20 14:31
Duplicate of #126. Closing.

**Closed by reckart** 2015-09-20 14:31 UTC
Labels: Annotation, bug
