### ISSUE TITLE
Feature Request - annotating with tag_name but selecting with tag_description

### ISSUE THREAD

**Issue by luto65** [webanno/webanno#523] opened 2017-06-09 07:14 UTC
## _Description_

This Issue is actually a Feature Request - aiming at facilitating the annotators job creating corpuses with coded entities.

## _Current situation_
Annotations are exported with the value specified in the "tag_name" of the tagset. For example using the the following tag
`{ "tag_name" :"H1" , "tag_description" :"Headache" }`
the UI will show "H1" in the possible pull down values, and "Headache" in the description field of the pop-up window.
When the annotator selects "H1" from the pull down,  then the annotation tag (e.g.also  the XML export) is "H1". 
This is inefficient, since it requires that the annotator knows the codes required.
If alternatively "Headache" is used as tag name, then this results in "Headache" in the XML export and this is inconvenient when comparing corpuses tagged automatically (since the taggers usually would deliver a "code" and not a "description".

## _Proposed scenario_
The annotator pull downs "Headache" and then "H1" is used as annotation tag (e.g. in the XML export)
The annotator can therefore focus on her/his knowledge (usually by rapidly selecting from the pulldown list) and the result of her/his work is then encoded using the specifically defined codes.

**Comment by reckart** [comment] 2017-06-09 07:58
My idea how to implement this would be adding a new field `tag_title` and if that field is not empty, then it would show in the UI instead of the `tag_name`.

**Comment by luto65** [comment] 2017-06-09 08:20
What about "uri"

**Comment by reckart** [comment] 2017-06-09 08:24
I think after adding the `tag_title` then you should probably use the "uri" for the `tag_name` if you care about it - otherwise it wouldn't end up in the XMI/CAS.

**Comment by reckart** [comment] 2017-07-17 10:39
Duplicate of #75.

**Comment by reckart** [comment] 2017-07-17 10:39
So, I have been thinking about this more...

Actually, this seems to clash with the input field being a combobox and with the "extensible tagset" functionality. Would a new tag entered by the user be the short or the long name. Both would be strange.

I don't see this happening with the current concept of tagsets and string value feature editors in WebAnno.

**Closed by reckart** 2017-07-17 10:39 UTC
Labels: Annotation, enhancement, Settings
