### ISSUE TITLE
No option for deleting features of layers?

### ISSUE THREAD

**Issue by Ratatam123** [webanno/webanno#429] opened 2017-02-02 11:23 UTC
Hi, 
how come there is no option for deleting features of layers (or is there)? It would really come in handy when one could get rid of certain features that don't prove to be useful the process of annotation.

**Comment by reckart** [comment] 2017-02-05 20:16
Indeed ;) Closing as duplicate of #368.

**Closed by reckart** 2017-02-05 20:16 UTC
Labels: duplicate
