### ISSUE TITLE
version downgrade issue

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1611] opened 2020-02-24 12:04 UTC
Hi 

For some reason, I have to downgrade my current 3.6.x version with 3.5.x version. So, I just replaced the war file. This throws following error.

ERROR [SYSTEM] SpringApplication - Application startup failed
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [de.tudarmstadt.ukp.clarin.webanno.brat.metrics.BratMetricsImpl@7cb1f4d8] with key 'bratMetricsImpl'; nested exception is javax.management.InstanceAlreadyExistsException: de.tudarmstadt.ukp.clarin.webanno.brat.metrics:name=bratMetricsImpl,type=BratMetricsImpl

Any help is appreciated. Thanks.

**Comment by reckart** [comment] 2020-02-24 12:08
I don't know the cause for this particular error message, but I doubt WebAnno 3.5.x runs on a database scheme that has already been upgraded to WebAnno 3.6.x. If you need to use an old version, then install this old version as a second copy using a different home folder / database. If you need to move a project from WebAnno 3.6.x ot 3.5.x, you can try exporting it from 3.6.x and then importing it into the parallel-running 3.5.x. There is no guarantee this works. WebAnno is not meant to be downgradable.

**Comment by reckart** [comment] 2020-03-17 13:57
Closing as no further input was provided.

**Closed by reckart** 2020-03-17 13:57 UTC
Labels: Support request
