### ISSUE TITLE
Interactivity is lost

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#77] opened 2015-08-15 01:39 UTC
Steps to recreate.

1. Open a document for Annotation which already has existing Lemma and POS type annotations.
2. Double click on any Lemma type annotation.
3. Double click on several different POS type annotation.
4. Try to click on any different Lemma type annotation now, the FeaturePanel doesn't change. It shows some processing but nothing changes.

In logs, you only get "The [Lemma] annotation has been created/updated."

**Comment by reckart** [comment] 2015-08-15 07:57
Did you create the document / lemma / pos from scratch or import them from a file?
What format did the file have?

**Comment by reckart** [comment] 2015-08-15 18:37
Diagnosis classifies this one as a duplicate of #8: CAS contained subtypes of a layer type via direct import from XMI files - such subtypes are not supported by WebAnno right now.

Duplicates #8.

**Closed** 2015-08-15 18:38 UTC
Labels: bug, duplicate

**Comment by reckart** [comment] 2015-08-15 18:42
It is basically the same thing as #8, but #8 is in monitoring while this one is in annotation - so removing the duplicate.

Anyway, commit f9fce58c66d1203715831b57e3f8535d724db14f turns this at least from an internal error/loss of interactivity into a proper error message.
