### ISSUE TITLE
Switching between layers deletes the annotation

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#276] opened 2016-05-19 15:02 UTC
When changing the layer of an existing annotation, the annotator is asked "Are you sure you want to delete the existing annotation?". A few hours ago, clicking on "yes" led to the actual layer change. Now, the annotation is deleted. When trying to assign a new annotation, an error message ocurrs: "[null] is not in the tag list. Please choose form the existing tags."
Choosing other tokens now leads to the same error. 
A part from the deletion itself, there is a typo in the error message.

I am working with WebAnno -- 3.0.0-beta-2 (2016-04-05 22:19:45, build b07b2897193cb8add658f0d3a6cb1008e490afc1) on Chrome.

**Comment by sholschneider** [comment] 2016-05-19 15:21
Trying to assign span annotations to a token without deleting anything beforehand leads to the same result. So the problem does not start with the attempt to switch layers.

**Comment by reckart** [comment] 2016-05-19 16:18
May be a duplicate of https://github.com/webanno/webanno/issues/207 ?

**Comment by sholschneider** [comment] 2016-05-19 16:34
Sounds similar, except it worked at the beginning. The problems started after having annotated ~100 sentences of the same file.

**Comment by reckart** [comment] 2016-05-19 20:25
Closing as duplicate of #207 Problem with null in tagset.

**Closed by reckart** 2016-05-19 20:25 UTC
Labels: Annotation, bug, duplicate
