### ISSUE TITLE
Exporting Data for Custom Layers/Tagsets

### ISSUE THREAD

**Issue by johnvblazic** [webanno/webanno#962] opened 2018-05-30 01:58 UTC
Hi,

Is there any further set up I need to do to have information on custom layer and tagset annotations show up in the exported files beyond creating them? I've created some layers and tagsets for testing and have tried to export them in different file formats to see what the output looks like. The export completely fails (i.e. errors out gracefully, returning me to the document selection screen) on the WebAnnoTSV3 format and I don't see it being printed out on any of the other formats.

Thanks,
John

**Comment by reckart** [comment] 2018-05-30 05:57
The TSV files have a header explaining the meaning of the columns. Not sure what you mean abut the tagsets. Can you provide an example?

**Comment by reckart** [comment] 2018-05-30 06:09
Ok, reading this a second time, I think I get a better idea what you are looking for.

Of the supported formats, only XMI and TSV support custom layers. The other formats have fixed semantics. That is why e.g. for CoNLL 2006, you have no header which describes the columns because the meaning of the columns is already fixed by the format (to specific built-in layers).

When you export as XMI, you actually get a ZIP  file which contains the actual UIMA CAS XMI file plus a `typesystem.xml` file which describes all the layers (built-in as well as custom).

In both cases (XMI and TSV) tagsets are not explicitly included. You can export tagsets separately via the tagsets tab in the project settings.

What kind of error do you get when you try exporting your data in WebAnnoTSV3 and which WebAnno version are you using?

**Comment by johnvblazic** [comment] 2018-05-30 06:18
I'll try the XMI in a second, but here is the error and the short part of the stack trace around the null pointer exception. Most of the stack trace is just a bunch of spring traces

2018-05-29 23:15:24 ERROR [admin] PrimitiveAnalysisEngine_impl - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:416) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:318) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[uimaj-core-2.10.2.jar!/:2.10.2]

...... skipping the hundreds of lines of spring traces......


Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XCasDocumentBuilder.scanUnitForAmbiguousSlotReferences(Tsv3XCasDocumentBuilder.java:303) ~[webanno-io-tsv-3.4.0.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XCasDocumentBuilder.of(Tsv3XCasDocumentBuilder.java:224) ~[webanno-io-tsv-3.4.0.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3XWriter.process(WebannoTsv3XWriter.java:56) ~[webanno-io-tsv-3.4.0.jar!/:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	... 178 more

**Comment by reckart** [comment] 2018-05-30 06:21
@johnvblazic thanks - that looks like a bug. Could you provide me with an export of your project (select format "Binary CAS") to reproduce and fix it?

**Comment by johnvblazic** [comment] 2018-05-30 06:21
Here's the error from XMI

2018-05-29 23:19:44 ERROR [admin] PrimitiveAnalysisEngine_impl - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: null
	at de.tudarmstadt.ukp.clarin.webanno.xmi.XmiWriter.process(XmiWriter.java:86) ~[webanno-io-xmi-3.4.0.jar!/:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:318) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) ~[uimaj-core-2.10.2.jar!/:2.10.2]

...... skipping the hundreds of lines of spring traces......

Caused by: org.xml.sax.SAXParseException: Trying to serialize non-XML 1.0 character: 0xc at offset 3,066 in string starting with                                                                                        Execution Ver
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:387) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:285) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1212) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1262) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1159) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:512) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:327) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:295) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at de.tudarmstadt.ukp.clarin.webanno.xmi.XmiWriter.process(XmiWriter.java:78) ~[webanno-io-xmi-3.4.0.jar!/:?]
	... 180 more

**Comment by johnvblazic** [comment] 2018-05-30 06:27
@reckart  there's some client data in the project that I can't export and share. I'm about to head to bed, but I'll generate a new project in the morning and see if I can get the error to reproduce and share that. Any idea as to what the bug might be?

Having looked at working exports from the standard layers and tagsets, I would prefer to use the TSV format anyhow, so I'd like to get that working. I'll also see if I can replace the characters that are causing the XML to bomb out. I'm guessing the XML export handles UTF-8?

**Comment by reckart** [comment] 2018-05-30 10:10
@johnvblazic The XMI export should handle Unicode and does export in UTF-8 - except that XML 1.0 defines that several characters are invalid. That is alleviated a bit with XML 1.1, but there are still some characters that are invalid.

For the NPE in the TSV case - it turned out it was rather easy to adapt an existing unit test to the case so I could reproduce it. It was a special edge-case that had not been considered so far. While looking into it, I found a second edge-case that also hadn't been considered so far. Both should be addressed by #963.

**Closed** 2018-06-02 16:13 UTC
Labels: ❓Question
