### ISSUE TITLE
Unable to export annotated documents

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1605] opened 2020-02-17 13:28 UTC
Hi

I tried exporting documents in JSON format. Few weeks ago, it worked but now I am getting following errors. I have two installations of webanno.

In first webanno instance, I get - 
Unexpected error during project export: EOFException:

In second webanno instance, I get - 
Invalid project export state after export: de.tudarmstadt.ukp.clarin.webanno.ui.project.export.ProjectExportPanel$ProjectExportForm$3@613df48a

Not sure, why I am getting these errors now. I am using WebAnno -- 3.5.7 server version.

**Comment by reckart** [comment] 2020-02-17 13:36
It is a bit hard to tell - but I can tell you that there have been various iterations of improvements and fixes to the export functionality since 3.5.7. Can you reproduce the problem with WebAnno 3.6.4?

**Comment by sonu-gupta** [comment] 2020-02-24 12:06
I am bound to use 3.5.7.  Any workarounds?

**Comment by reckart** [comment] 2020-02-24 12:08
Why do you need to use 3.5.7?

**Comment by reckart** [comment] 2020-03-17 13:57
Closing as no further input was provided.

**Closed by reckart** 2020-03-17 13:57 UTC
Labels: Support request
