### ISSUE TITLE
Changing the document status takes a long time

### ISSUE THREAD

**Issue by mujdricza** [webanno/webanno#90] opened 2015-08-26 16:39 UTC
If I would like to change the status of a document in Monitoring, it takes upto 15 seconds time.

Is it normal? Could it be done in shorter time?

The problem is, that I didn't assumed this behaviour and I have upto 400 small documents I should manage -- not all annotators should see all the files, so I have to disable these files for certain annotators.

(I know, I could merge files together by myself, too... But the question is probably also interesting for other larger projects.)

**Comment by reckart** [comment] 2015-08-26 17:19
Apparently, the performance doesn't scale well with the number of documents. 
Do you do this while the you have some feature selected for agreement?

Even if this was faster, it would probably be very tedious to manually change 400 documents for n annotators, right?

I guess what you would need is a functionality where you can say "assign each document to X annotators" which would distribute work equally amongst the annotators - is that what you are trying to do?

**Comment by mmev** [comment] 2015-08-27 10:40
I did not select any features for agreement in this case. 

I would like to have a functionality to add/disable a whole set of documents for user x, and just loading the selection once, and not to load them automatically for each change.

The automatic distribution of the documents among the annotators was an interesting feature, too. (However for now, I have to organize the documents by myself.)

**Comment by reckart** [comment] 2015-08-27 21:29
The click on a cell in the table should be an immediate action. It should not take 15 seconds. It should not reload any data other than the contents of that cell (unless an agreement calculation is active). Still, if you have 400 documents and n annotations, you'd be horribly busy even if this worked as fast as it should.

**Comment by reckart** [comment] 2015-08-27 21:57
I've just had a brief look at this. The main problem appears to be that currently the whole table is re-rendered on a click (not only the cell) and that triggers many database operations. Doing this properly would entail a major rewrite of the whole document status table. I'm not sure if the operation can be easily limited to the single cell either.

**Comment by sholschneider** [comment] 2016-09-15 08:47
As long as unlocking takes so much time, it would be quite handy if the default state was "locked" instead of "unlocked". If you have a project with more than four annotators, it's exhausting to double-click every single file that isn't assigned to an annotator. Additionally you wouldn't have to tell the annotators to stop annotating every time you upload new files.

**Comment by sholschneider** [comment] 2016-10-31 16:39
I know this is nothing new but to emphasize the additional work that is caused by the time-consuming "locking of documents": As our project has grown up to 177 files now and includes 6 annotators, it takes 56 seconds now to lock only one document for one annotator. As we have a new annotator starting tomorrow, I just spent 165 minutes only to lock documents. – And I am not even done with this week's locking.

**Comment by reckart** [comment] 2016-11-01 10:58
@seyyaw do you see any way of speeding this up without a major rewrite?

**Comment by seyyaw** [comment] 2016-11-02 21:16
@reckart I discuss with @ChrisBieTUDA  and he suggests to make the computation of agreements to be on demand (for example click a **compute** button) instead of computing the agreement on every lock/unlock actions. What do you think?

**Comment by reckart** [comment] 2016-11-03 06:48
@seyyaw as far as I remember, the computation of agreement is not the problem. It is only calculated if a feature is selected and I believe even only if the feature is changed. 

When I checked last time, the problem that makes the monitoring table slow is related to the monitoring table itself - it seems to always load/save all the data in the table, even if only a single cell is changed.

**Comment by reckart** [comment] 2021-06-18 20:22
The new workload management UIs in INCEpTION are very fast in changing the state of documents and even allow bulk actions.

**Closed by reckart** 2021-06-18 20:22 UTC
Labels: Module: Monitoring, 🆕Enhancement, 🕶️UX
