### ISSUE TITLE
Annotation: "Constraints (...).txt does not exist"

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#446] opened 2017-02-22 16:45 UTC
This isn't a huge problem as annotation is still possible. However, working with WebAnno -- 3.1.0-SNAPSHOT (2017-02-12 22:10:50, build 96280b8b14735b8574ef49310206d471eebfb2eb) on Windows 8.1 with Chrome, annotators get an error message "constraints (...).txt does not exist" and the annotation file isn't loaded when the respective layers in the "Settings"-checkbox aren't checked. 
![capture](https://cloud.githubusercontent.com/assets/13764947/23221940/aab275a2-f926-11e6-9015-410da53238b2.PNG)

**Comment by reckart** [comment] 2017-08-11 20:21
Seems to be a duplicate of #448. Closing this one was well since we have no idea how to reproduce.

**Closed by reckart** 2017-08-11 20:21 UTC
Labels: bug, Constraints

**Comment by reckart** [comment] 2019-01-13 23:51
The cause of this problem was most likely #1164 which finally has been fixed now.
