### ISSUE TITLE
RTL-script: rendering with quotation marks

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#265] opened 2016-05-09 12:39 UTC
I used WebAnno 2.3.0 in the standalone version. Browsers: Chromium / Firefox and for verification / falsification: Safari. 

I annotated parts of an arabic sentence. With Chromium and Firefox I experienced wrong rendering of the span annotation. The last two words without the quotation mark (annotation 23) are being displayed correctly.
![23-chrome](https://cloud.githubusercontent.com/assets/19265315/15112927/921e6730-15f1-11e6-9c85-1f52449a95d7.png)

But if I annotate parts including a quotation mark – and that will occur quite frequently in our case – the span will only cover the quotation mark itself.
![12-chrome](https://cloud.githubusercontent.com/assets/19265315/15112881/519a629a-15f1-11e6-826e-92c1898998da.png)

In Safari both annotations are being displayed correctly, although the tooltip shows the quotation mark as an opening one before the أو.
![12-safari](https://cloud.githubusercontent.com/assets/19265315/15112954/bcca4ff8-15f1-11e6-83c5-b734f2c00e2e.png)

**Comment by reckart** [comment] 2016-05-09 13:10
Thank you for the report! Btw. if you have any theory what could cause these problems, it would be great to know. 

Could you maybe attach a file by which this problem can be reproduced?

Is the quote an arabic (RTL) character, or is it a "normal" LTR character?

Is it part of the token or a separate token?

**Comment by TFeige** [comment] 2016-05-09 14:06
Attached is the source. Actually it's an normal quotation mark (U+0022), so it is mixed and it is a separate token. 

I will try to do some more testing with arabic (RTL) tomorrow. 
[test.txt](https://github.com/webanno/webanno/files/255130/test.txt)

**Comment by reckart** [comment] 2016-05-17 15:35
I have imported the test.txt file you linked above as a plain text file into WebAnno -- 3.0.0-SNAPSHOT (2016-05-12 20:43:29, build 57f8a1f6e93f77121d99a9dba77c1abae1c1453c).

Then I annotated the quotation mark.

Here a screenshot from Chrome (Version 50.0.2661.102 (64-bit) OS X):

![2016-05-17_17-28-01](https://cloud.githubusercontent.com/assets/1410238/15328317/c3af2f32-1c54-11e6-8bf7-597d0a3385fc.png)

... and another screenshot from Safari (Version 9.1.1 (11601.6.17) OS X)

![2016-05-17_17-27-11](https://cloud.githubusercontent.com/assets/1410238/15328308/bbe8ca6a-1c54-11e6-8889-23d12a19b709.png)

... and another screenshot from Firefox (Version 46.0.1 OS X)

![2016-05-17_17-30-17](https://cloud.githubusercontent.com/assets/1410238/15328408/0e53d632-1c55-11e6-8dab-df5f50b8940a.png)

Mind that for the screenshots, I did annotate the quotation mark in the browser - I didn't just reload the annotated document in another browser.

Maybe it was a problem fixed with WebAnno 3? Does the problem occur for you as well when you try annotation with a POS annotation or only for your custom "test" layer?

**Comment by reckart** [comment] 2016-05-17 15:36
If this occurs only for the custom layer, this may be a variant of issue #156.

**Comment by TFeige** [comment] 2016-05-18 15:50
Thanks for the feedback. From my point of view it has to do with the directionality, rather than tokenization. 

POS annotation doesn't work, because the problem lies in multi-token annotation. If you annotate the two words before the comma as well (layer Named Entity should do the trick), the result will be like in the screenshot: 
![v3-chromium](https://cloud.githubusercontent.com/assets/19265315/15364936/a309c57e-1d1e-11e6-83ff-cd6fe30bb177.png)

The custom layer (without lock to token or multiple token) has the same problem.
![v3-chromium_2](https://cloud.githubusercontent.com/assets/19265315/15365491/b3458bd8-1d20-11e6-88f2-8213de1609cc.png)

Note the representation of the annotation in the tooltip. The comma is at the first position (seen from the right).

**Comment by reckart** [comment] 2016-05-18 16:01
Ok, I tried with a NamedEntity multi-token annotation over the quotation mark and including the two(?) words before it (reading right to left).

I made the annotation with Safari (Version 9.1.1 (11601.6.17) OS X) - and here it also seems to render correctly (minus that the parenthesis in the annotation label is placed into the middle of the label):

![2016-05-18_17-56-32](https://cloud.githubusercontent.com/assets/1410238/15365877/360b0aba-1d22-11e6-97c0-855acde189b0.png)

Opening the same annotation then with Chrome (Version 50.0.2661.102 (64-bit) OS X) or Firefox (Version 46.0.1 OS X), it renders as you report - broken with the label only being attached to the quotation mark:

![2016-05-18_17-57-18](https://cloud.githubusercontent.com/assets/1410238/15365909/592c4ed2-1d22-11e6-9649-f41e1c4a4f55.png)

So we seem to have a browser-specific bug for Chrome/Chromium/Firefox.

**Comment by TFeige** [comment] 2016-05-18 16:06
Confirmed. I checked with UIMA XMI output. The annotation is correct. Only the representation is broken for Firefox and Chrome /ium.

**Comment by reckart** [comment] 2016-05-19 22:01
Looks like Chrome and Safari use different strategies to determine character positions in an SVG element.

Chrome (~ visualizer.js:1307):

```
char 0 [ث] begin:7.56640625 end:-1.70751953125 width:9.27392578125
char 1 [م] begin:-1.70751953125 end:0 width:1.70751953125
char 0 [م] begin:26.12060546875 end:21.72802734375 width:4.392578125
char 1 [ض] begin:21.72802734375 end:6.72216796875 width:15.005859375
char 2 [غ] begin:6.72216796875 end:4.14501953125 width:2.5771484375
char 3 [ة] begin:4.14501953125 end:0 width:4.14501953125
char 0 [ذ] begin:14.8916015625 end:10.50537109375 width:4.38623046875
char 1 [ل] begin:10.50537109375 end:3.9228515625 width:6.58251953125
char 2 [ك] begin:3.9228515625 end:0 width:3.9228515625
char 3 [،] begin:14.8916015625 end:19.03662109375 width:4.14501953125
```

Safari (~ visualizer.js:1307): 
```
[Log] char 0 [ث] begin:0 end:9.288787841796875 width:9.288787841796875
[Log] char 1 [م] begin:9.288787841796875 end:7.578531742095947 width:1.7102560997009277 
[Log] char 0 [م] begin:0 end:4.3996171951293945 width:4.3996171951293945
[Log] char 1 [ض] begin:4.3996171951293945 end:19.429523468017578 width:15.029906272888184 [Log] char 2 [غ] begin:19.429523468017578 end:22.01080322265625 width:2.581279754638672 
[Log] char 3 [ة] begin:22.01080322265625 end:26.162464141845703 width:4.151660919189453 
[Log] char 0 [ذ] begin:0 end:4.393259525299072 width:4.393259525299072
[Log] char 1 [ل] begin:4.393259525299072 end:10.986328125 width:6.593068599700928
[Log] char 2 [ك] begin:10.986328125 end:14.91546630859375 width:3.92913818359375
[Log] char 3 [،] begin:14.91546630859375 end:19.067127227783203 width:4.151660919189453
```

Particularly notable is that the counting direction in Safari is monotonous in Safari when hitting the comma `[،]` while in Chrome it jumps around wildly.

**Comment by reckart** [comment] 2016-05-19 22:47
I have implemented an alternative method of measuring the text width using the width of individual characters instead of trying to access the coordinates of characters directly. That appears to fix/equalize the rendering across browsers. Is probably a bit slower though

**Closed by reckart** 2016-05-19 22:47 UTC
Labels: Annotation, browser-chrome, browser-firefox, RTL
