### ISSUE TITLE
When switching pages via "Go to" during curation, only the upper annotation frame is updated

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#310] opened 2016-07-04 19:14 UTC
I am using WebAnno -- 3.0.0-SNAPSHOT (2016-07-04 10:16:41, build f3f630733a746875be7d0cd3cdab07856299e6c1) on Chrome. When switching pages via "Go to" during curation, only the upper annotation frame is updated. The user's view stays on the page I have chosen before. If I don't click too fast (type "55" into "go to"...wait a bit...click "go to"), I don't have that problem. Reloading the page doesn't solve the case, but I can navigate to the desired page while clicking on "Next", then on "Prev.". Still, it is a bit unhandy during the curation process.

**Comment by seyyaw** [comment] 2016-07-09 10:47
I could not repo this.

**Comment by reckart** [comment] 2016-12-05 20:08
Could this be a duplicate of #392?

**Comment by sholschneider** [comment] 2017-02-19 21:16
As far as I understand it, #392 describes something else. The problem I described for WebAnno -- 3.0.0-SNAPSHOT (2016-07-04 10:16:41, build f3f6307) reoccurres in WebAnno -- 3.1.0-SNAPSHOT (2017-02-12 22:10:50, build 96280b8b14735b8574ef49310206d471eebfb2eb), using Chrome on Windows 8.1. I just realized why you couldn't reproduce it. Everything works fine as long as you actually click on "Go to". The problem only occurres when you push the "E
![capture](https://cloud.githubusercontent.com/assets/13764947/23106665/1a15628e-f6f1-11e6-9599-4b985bf4f5e4.PNG)
nter"-key instead. Then, only the curation frame is updated. After having incorrectly switched the pages, "Go to" is inactive. "Next" and "Prev." still work.

**Closed** 2017-08-07 13:47 UTC
Labels: Annotation, bug
