### ISSUE TITLE
Monitoring: Locking and unlocking documents very slow

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#322] opened 2016-08-19 08:12 UTC
Locking and unlocking documents for users is very slow (>10 seconds per click). I am using WebAnno Testing 3.0.0-SNAPSHOT (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155) with Chrome on Windows 8.1.

**Comment by reckart** [comment] 2016-08-19 09:53
Duplicate of #90.

**Comment by reckart** [comment] 2017-01-25 14:26
Closing as being a duplicate.

**Closed by reckart** 2017-01-25 14:26 UTC
