### ISSUE TITLE
Number of predefined layers

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#630] opened 2017-08-24 19:37 UTC
Number of predefined layers get crazy, esp since they are all enabled. Add comment layer as a default and disable others per default?

Tested by: @ChrisBieTUDA

**Comment by reckart** [comment] 2017-08-24 19:37
I have no idea what you are talking about.

**Comment by reckart** [comment] 2017-08-24 20:36
I think I would consider this is a duplicate of https://github.com/webanno/webanno/issues/469 

I suppose you imagine that we add some "comment" layer that only has a single feature "comment" and that would always be there? The current built-in layers allow users to quickly start with annotation types that are supported by most annotation formats supported by WebAnno. If we start them off with a "comment" layer that is not supported by most formats, I think it will trigger many questions.

I think that https://github.com/webanno/webanno/issues/469 provides a good description of the usability issue and proposes a good solution.

**Comment by reckart** [comment] 2017-12-01 11:03
Closing as duplicate of #469.

**Closed by reckart** 2017-12-01 11:03 UTC
Labels: duplicate, enhancement, Settings, usability
