### ISSUE TITLE
Correction CAS gone missing

### ISSUE THREAD

**Issue by mainio29** [webanno/webanno#444] opened 2017-02-21 21:08 UTC
Our Webanno tool was working fine but from past few days few users have reported “internal error” messages with certain files that render them unable to access their files within WebAnno.
In addition, we are getting Project export cancelled issue too. 
I have attached the screenshot of both issues. Would really appericiate your guidance on this. 

Tool: WebAnno 3.0.1
Platform: Windows Server 2008 R2
Tomcat Version: Apache Tomcat/8.5.11	
JVM Version: 1.8.0_111-b14

![image 5](https://cloud.githubusercontent.com/assets/25938635/23184970/58bb9f9a-f88a-11e6-9af2-1ef648891152.png)
![image 4](https://cloud.githubusercontent.com/assets/25938635/23184969/58bb1e58-f88a-11e6-932d-9a6597789fdc.png)

**Comment by reckart** [comment] 2017-02-21 21:10
Try adding this line to your settings.properties file to get more details:

```
debug.showExceptionPage=true
```

Also, what are you trying to do when you get the internal error?

**Comment by reckart** [comment] 2017-02-21 21:12
Please also add the following lines to your settings.properties:

```
debug.casDoctor.checks=AllFeatureStructuresIndexedCheck,LinksReachableThroughChainsCheck,FeatureAttachedSpanAnnotationsTrulyAttachedCheck,NoZeroSizeTokensAndSentencesCheck
debug.casDoctor.fatal=true

```

**Comment by mainio29** [comment] 2017-02-21 21:20
Hi, 
Thank you for your reply. I am quite new to the tool. So would you mind to share me where can I get setting. properties in my tool. I try to explore in C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\webanno. 

Regarding Internal issue, This renders the users unable to access their annotation files. In some cases, this is only a file or two, but with others, it seems it has been all the files made available to them in their project folders. 

Not only that, this bug does not allow me to export their projects in hopes of reloading them to fix the issue. Rather, I get an error message that the "Project export cancelled."

**Comment by reckart** [comment] 2017-02-21 21:23
The `settings.properties` file is the one where you placed your database connection parameters too. It resides in the directory that you passed to WebAnno using the "-Dwebanno.home" parameter on startup. Looking at the screenshot, it appears that you are using a MySQL database, so you must have created such a file somewhere.

In general, exporting and re-importing a project won't fix any problems. 

My best guess at this point is that there is some inconsistency in the annotation files. With a little luck, we can use the "casDoctor" to locate them and possible to repair them.

**Comment by mainio29** [comment] 2017-02-21 21:37
In addition, From Tomcat 8, when I press "Find Leaks", it shows the message as:
The following web applications were stopped (reloaded, undeployed), but their
classes from previous runs are still loaded in memory, thus causing a memory
leak (use a profiler to confirm):
/webanno
This might help to know my issue. I have installed WAR file for Webanno using Tomcat Deploy tool.

**Comment by reckart** [comment] 2017-02-21 21:40
No, that message about the leak is normal. It is not related to your issue.

**Comment by mainio29** [comment] 2017-02-21 21:48
I deployed webanno WAR file into tomcat server I had tomcat already installed so I just skipped the installing tomcat steps from installation manual. I could not find this file settings.properties. Is this file supposed to be installed with deployment process?

**Comment by reckart** [comment] 2017-02-21 21:51
No, the settings.properties file must be created manually. Did you specify a system property called "webanno.home" somewhere? How did you tell WebAnno to make use of MySQL? I'm pretty sure that your WebAnno is using MySQL, because otherwise there should be a warning at the bottom of the screen like "USE THIS INSTALLATION FOR TESTING ONLY -- AN EMBEDDED DATABASE IS NOT RECOMMENDED FOR PRODUCTION USE".

**Comment by mainio29** [comment] 2017-02-21 22:53
Yes, I am using MYSQL as my Webanno data are stored in C:\ProgramData\MySQL\MySQL Server 5.7\Data\webanno . I think, I haven't configure anything such for system property. First, I create a user for WebAnno in Mysql CLI and I modify databaseContext.xml from "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\webanno\WEB-INF" to define the database connection but in Guideline it was written /srv/webanno/settings.properties . So I haven't create any settings. properties. Did I configure wrongly ? But tool was running fine. 
Note: I am using Windows Server 2008 R2.

**Comment by reckart** [comment] 2017-02-21 22:57
You're not supposed to be changing the databaseContext.xml no. You're supposed to be setting a system property on your Tomcat. Have a look at our installation instructions, in particular any references to "webanno.home" and "settings.properties". https://webanno.github.io/webanno/releases/3.0.1/docs/admin-guide.html

By default, WebAnno looks for the settings.properties in userhome/.webanno/settings.properties. "userhome" would be the home of the user under which your Tomcat is running. You could try that.

**Comment by mainio29** [comment] 2017-02-22 12:02
Thank you for your kind word. But I am totally speechless now as I am not able to figure out this "settings.properties". Let me explain what I did.
- I use apache-tomcat-8.5.11.exe file to install Tomcat. 
- I install MySQL manually and create database for Webanno over tere. 
- I downloaded Webanno.war file , and then from http://127.0.0.1:8080/manager/html, I deploy WAR file. 
My webanno tool is in "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\webanno" beside that my data of Webanno is in "C:\ProgramData\MySQL\MySQL Server 5.7\Data\webanno". 
I try to search webanno.home, but I couldn't get success on it. 
Is my configuration missing something. And if I have to created "settings.properties" manually, then in this case, where will be the default location for it. And what script or line I have to add it as it will be empty when I create manually.

**Comment by reckart** [comment] 2017-02-22 12:11
I am unfortunately not familiar with Tomcat on Windows. Check if there is a "setenv.bat" file in your Tomcat folder and check for a JAVA_OPTS variable inside it. Try adding to that variable `-Dwebanno.home=C:\Program Files\WebAnno`. Then create a text file `C:\Program Files\WebAnno\settings.properties` and put the lines in that I mentioned above.

After restarting your Tomcat, check the `catalina.out` log file. There should be a message like

```
2017-02-22 13:09:27  INFO [localhost-startStop-1] [SYSTEM] (WebAnnoApplicationContextInitializer) -   _      __    __   ___                
2017-02-22 13:09:27  INFO [localhost-startStop-1] [SYSTEM] (WebAnnoApplicationContextInitializer) -  | | /| / /__ / /  / _ | ___  ___  ___ 
2017-02-22 13:09:27  INFO [localhost-startStop-1] [SYSTEM] (WebAnnoApplicationContextInitializer) -  | |/ |/ / -_) _ \/ __ |/ _ \/ _ \/ _ \
2017-02-22 13:09:27  INFO [localhost-startStop-1] [SYSTEM] (WebAnnoApplicationContextInitializer) -  |__/|__/\__/_.__/_/ |_/_//_/_//_/\___/
2017-02-22 13:09:27  INFO [localhost-startStop-1] [SYSTEM] (WebAnnoApplicationContextInitializer) - Settings: C:\Program Files\WebAnno\settings.properties
```

**Comment by reckart** [comment] 2017-02-22 12:13
@mainio29 actually, forget what I said :) check in your catalina.out what folder the line

```
[SYSTEM] (RepositoryServiceDbData) - Repository: ...
```

points to and create your settings.properties file in the parent of that folder.

**Comment by mainio29** [comment] 2017-02-23 12:38
I manage finally to get more issue info. It might be helpful for other windows users. The folder is in 
-Dwebanno.home=C:\Windows\System32\config\systemprofile\.webanno

I addded the line and m getting following error: 
![issue1](https://cloud.githubusercontent.com/assets/25938635/23259423/b0ca97c6-f9d5-11e6-8caf-c5dfb6fcf012.JPG)
![issue2](https://cloud.githubusercontent.com/assets/25938635/23259424/b0e1fc22-f9d5-11e6-9562-8a0e4eae170d.JPG)

**Comment by mainio29** [comment] 2017-02-23 13:48
Full Error message:
Stacktrace

Root cause:

java.lang.NullPointerException
     at de.tudarmstadt.ukp.clarin.webanno.brat.controller.BratAjaxCasUtil.getAddr(BratAjaxCasUtil.java:128)
     at de.tudarmstadt.ukp.clarin.webanno.webapp.page.correction.CorrectionPage$6.load(CorrectionPage.java:362)
     at de.tudarmstadt.ukp.clarin.webanno.webapp.page.correction.CorrectionPage$6.load(CorrectionPage.java:336)
     at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:124)
     at org.apache.wicket.Component.getDefaultModelObject(Component.java:1612)
     at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1640)
     at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:131)
     at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2536)
     at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
     at org.apache.wicket.Component.internalRender(Component.java:2366)
     at org.apache.wicket.Component.render(Component.java:2294)
     at org.apache.wicket.ajax.XmlAjaxResponse.writeComponent(XmlAjaxResponse.java:128)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeComponents(AbstractAjaxResponse.java:226)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeTo(AbstractAjaxResponse.java:151)
     at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:359)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Unknown Source)

Complete stack:

org.apache.wicket.WicketRuntimeException: Exception in rendering component: [Component id = numberOfPages]
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2560)
     at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
     at org.apache.wicket.Component.internalRender(Component.java:2366)
     at org.apache.wicket.Component.render(Component.java:2294)
     at org.apache.wicket.ajax.XmlAjaxResponse.writeComponent(XmlAjaxResponse.java:128)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeComponents(AbstractAjaxResponse.java:226)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeTo(AbstractAjaxResponse.java:151)
     at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:359)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)

java.lang.RuntimeException: An error occurred while getting the model object for Component: [Component id = numberOfPages, page = de.tudarmstadt.ukp.clarin.webanno.webapp.page.correction.CorrectionPage, path = 3:numberOfPages.Label, isVisible = true, isVersioned = true, markup = [markup = file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/webanno/WEB-INF/classes/de/tudarmstadt/ukp/clarin/webanno/webapp/page/correction/CorrectionPage.html
<span wicket:id="numberOfPages"></span>, index = 0, current =  '<span wicket:id="numberOfPages">' (line 0, column 0)]]
     at org.apache.wicket.Component.getDefaultModelObject(Component.java:1617)
     at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1640)
     at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:131)
     at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2536)
     at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
     at org.apache.wicket.Component.internalRender(Component.java:2366)
     at org.apache.wicket.Component.render(Component.java:2294)
     at org.apache.wicket.ajax.XmlAjaxResponse.writeComponent(XmlAjaxResponse.java:128)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeComponents(AbstractAjaxResponse.java:226)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeTo(AbstractAjaxResponse.java:151)
     at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:359)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)

**Comment by reckart** [comment] 2017-02-23 13:52
Thanks, I'll see what I can find out.

**Comment by mainio29** [comment] 2017-02-23 13:59
Please help. I have seen you have guided a lot of people :) 

In brief, our file (that is giving internal error) is accessible from admin profile and there is no issue at all to open it. But when the user who is assigned this task, is getting internal error. This issue is increasing now as couple of users are reporting this issue. 

regarding the file format, as we’ve been originally been given the specification that it is CoNLL, but I suspect it may be CoNLL-U. Maybe that could be the cause of the internal error issue?

**Comment by reckart** [comment] 2017-02-23 14:38
@mainio29 assuming you have added the "casDoctor" lines to the settings.properties as indicated above we probably have a problem in the code and not in the data. However, to be able to reproduce this, it would be great if you could export your project for me (Projects -> Export (format "binary cas")) and send it to my privately. You can find my mail address [here](https://www.ukp.tu-darmstadt.de/people/senior-staff/dr-richard-eckart-de-castilho/).

**Comment by mainio29** [comment] 2017-02-23 15:12
I have added "casDoctor" in the line as following
debug.showExceptionPage=true
debug.casDoctor.checks=AllFeatureStructuresIndexedCheck,LinksReachableThroughChainsCheck,FeatureAttachedSpanAnnotationsTrulyAttachedCheck,NoZeroSizeTokensAndSentencesCheck
debug.casDoctor.fatal=true
I will send you the file soon in your email. 
Thank you so much for taking care of this.

**Comment by reckart** [comment] 2017-02-23 18:26
Ok, the problem were Windows newline characters that got swallowed when exporting the file as TSV3. I have now changed the code such that text is Java-escaped and then stored in the file. So the TSV format now looks like

```
#Text=This is line 1\r
#Text=and this is line 2 of a\tsentence.
```

**Comment by reckart** [comment] 2017-02-23 18:26
@amir-zeldes this change might be relevant to you.

**Comment by reckart** [comment] 2017-02-23 18:29
Hm, this change is not backwards compatible... if a text contained e.g. `\t` in a previously exported TSV3 file, it would now become a tab character... need to think if there is a better solution.

**Comment by mainio29** [comment] 2017-02-23 19:31
Hi Reckart, should I wait for some better solution or you suggest some additional step at my end.

**Comment by mainio29** [comment] 2017-02-23 20:45
Any update 😊

Regards,
Udhyan.

**Comment by reckart** [comment] 2017-02-23 20:48
New files now written as format 3.1. The reader detects if file is 3 or 3.1. In the latter case, Java-unescaping will happen. This should provide a smooth transition.

**Comment by reckart** [comment] 2017-02-23 21:14
@mainio29 sorry, I mixed up this issue and #447. Still need to look into this one...

**Comment by mainio29** [comment] 2017-02-23 21:17
I am waiting for the solution.

Regards,
Udhyan.

**Comment by reckart** [comment] 2017-02-23 22:07
@mainio29 do your users share accounts? I.e. are there multiple people logging in with the same user account - say "john" - at the same time and editing the same document?

**Comment by mainio29** [comment] 2017-02-23 22:10
Hi, no, not to my knowledge

**Comment by reckart** [comment] 2017-02-23 22:49
So it looks like for some reason the `CORRECTION_USER.ser` file is missing from some of the `annotation` folders in your project. You can probably simply copy the file over from another `annotation` folder under the same document. However, I don't know yet why this happens and how to fix it. The loading process on the correction page is a bit... well... funky. Did you upgrade your WebAnno recently? What version have you been using before?

**Comment by mainio29** [comment] 2017-02-23 22:51
I have installed directly 3.0.1 version as it is a fresh installation.

Regards,
Udhyan.

**Comment by mainio29** [comment] 2017-02-23 22:54
Did you manage to see my log. I have send you on your personal email.

Regards,
Udhyan.

From: Timilsina, Udhyan
Sent: Friday, February 24, 2017 12:51 AM
To: 'webanno/webanno' <reply@reply.github.com>; webanno/webanno <webanno@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [webanno/webanno] Correction CAS gone missing (#444)

I have installed directly 3.0.1 version as it is a fresh installation.

Regards,
Udhyan.

**Comment by reckart** [comment] 2017-02-23 22:56
Yes, but nothing in it I can make use of. I think the fix to the problem is re-writing the code in the correction page that loads a document. That code is a heap of spaghetti. I'm afraid that may take a moment, but I'll see what can be done.

**Comment by reckart** [comment] 2017-02-25 10:05
So my assumption is that the `loadDocumentAction()` didn't properly handle all the possible cases of annotation/correction CASes and DB metadata (not) existing. So I have refactored that code heavily and now it is more similar to the code from the AnnotationPage.

**Comment by reckart** [comment] 2017-02-25 10:20
Changes so far only affect 3.2.0-SNAPSHOT. Not yet ported to the 3.1.x branch.

**Comment by reckart** [comment] 2017-02-26 19:58
@mainio29 I've had a brief look at back-porting this fix to the 3.1.x branch, but it seems to be too much effort. The 3.2.x branch has undergone extensive refactoring with limited testing. I will do a "3.2.0-beta-1" release if you care to upgrade to that.

**Comment by mainio29** [comment] 2017-02-26 20:01
Hi Richard,
Thank you so much for your kind efforts. Yes we are ready to upgrade also if you think the upgrade will work.
Regards,
Udhyan.

Get Outlook for Android<https://aka.ms/ghei36>

**Closed** 2017-02-26 20:00 UTC
Labels: bug, Correction

**Comment by reckart** [comment] 2017-02-26 20:09
@mainio29 I'd strongly recommend a backup and some testing on your side. You should also be prepared to report issues that you may encounter with the beta version. Also, beta versions by default have extra consistency checks enabled that significantly slow down the annotation. You'd have to force-disable these checks for better reaction times. I don't think that so-far during the refactoring any code was changed would be critical in relation to such inconsistencies, so disabling these checks at this time should be ok. 

That said, you should bear in mind that this would be a beta software with the usual caveats and that WebAnno doesn't come with any guarantees or warranties. See [Apache License Section 7](https://www.apache.org/licenses/LICENSE-2.0). I'll drop a note here when the beta is available from the website.

**Comment by reckart** [comment] 2017-02-26 21:40
Here is the link to the beta version: https://webanno.github.io/webanno/downloads-beta/

If you want to disable the consistency checks, add this line to your `settings.properties` file:

```
debug.casDoctor.forceReleaseBehavior=true
```

**Comment by reckart** [comment] 2017-03-12 23:04
Btw, the reason for your problem is probably that the CAS for the virtual "CORRECTION_USER" is not included in exports. Thus when you export a project and then re-import it, it is missing and WebAnno wasn't able to re-create it. No data is lost here because the "CORRECTION_USER" CAS is just a conversion of the original document with no changes by any users. Actually, it is a relict that could be removed entirely nowadays because the concept of the INITIAL_CAS covers this case sufficiently.
