### ISSUE TITLE
Annotation: Documents are left out

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#440] opened 2017-02-11 16:28 UTC
Using WebAnno Testing (2017-02-10 23:26:06, build d25a081f72aba0dbed0c07d8f47a8baf0e779e53) with Chrome on Windows 8.1, documents are left out during the annotation process. It's always the document on the second line, regardless of the number of lines that are shown. The only way to access every line is to set the number of lines to 1. This occurred in several files, such as "Sentiment DB/15_05_21_e_2005025_21050215_classified_016.tsv".
![capture](https://cloud.githubusercontent.com/assets/13764947/22855363/b439a26c-f07f-11e6-8094-a835ed65704d.PNG)

**Comment by reckart** [comment] 2017-02-11 19:47
Assuming that you want to say that "sentences" are left out instead of "documents", then that sounds like a duplicate of the already known issue #20. Can you confirm that? Otherwise, I don't understand the bug description.

**Comment by sholschneider** [comment] 2017-02-12 11:40
Yes, I meant "sentences". Sorry for the confusion. We use the term "documents" inside the project as these pieces of text sometimes consist of more than one sentence. So it is indeed a duplicate.

**Comment by reckart** [comment] 2017-02-12 13:30
Closing as duplicate of #20.

**Closed by reckart** 2017-02-12 13:30 UTC
Labels: duplicate
