### ISSUE TITLE
Not deselecting edge annotation even after selecting a target node.

### ISSUE THREAD

**Issue by Simon-Will** [webanno/webanno#209] opened 2016-03-21 12:39 UTC
At my work in the CLARIN-D project concerned with semantic annotations, I noticed the following behavior starting with the new build from March 12 (i. e. probably starting with WebAnno 3.0.0): When I add an edge to a verb node to annotate a semantic role for it, the field for the target node says `<Select to fill>`, which is fine. But even when I have selected a target node, it still says that and I'm provided with the `Del`- and `Set`-Options for the edge (Clicking one of them throws an exception). To add another edge, I have to *reselect* the verb node by double-clicking it again. I strongly suppose that this is a bug, because it is annoying and has not been the case in previous versions.

Additionally, it leads to exceptions. I have experienced some exceptions, all of which (I suppose) stem from this problem. You can find them at [my page at Heidelberg's ICL](http://www.cl.uni-heidelberg.de/~will/webanno_exceptions/).( I'm sorry for the formatting of some of them. I only downloaded one with my web browser.)

I'm using WebAnno version `3.0.0-beta-1` (build `17c92399feb85cf0bb41ea82af74d99469b22186` from March 12) at `https://clarin.ukp.informatik.tu-darmstadt.de/webanno-testing/`.

I hope, you understood my description of the problem. I can add some screenshots if it's unclear. If you need additional information about the structure of our annotations, I will ask our administrator for it,

**Comment by reckart** [comment] 2016-03-21 13:02
Sounds like a duplicate of #186.

**Comment by Simon-Will** [comment] 2016-03-21 13:04
Oh, it does. I'm very sorry. I did check the other issues, but must have overlooked this one. Feel free to delete the issue.

**Comment by reckart** [comment] 2016-03-21 13:05
We'll keep it as additional information and for the links to the stack traces (which we should probably transfer to this tracker here).

**Comment by Simon-Will** [comment] 2016-03-21 13:07
I can add them later today. GitHub doesn't accept html-files. But renaming to .txt will probably suffice.

**Comment by reckart** [comment] 2016-03-21 13:08
Copy/pasting them should also work, preferrably within a verbatim block (starting and closing with three backtick characters on a line). We can also fix formatting/trim unnecessary parts of the trace ourselves.

**Comment by Simon-Will** [comment] 2016-03-24 16:20
I just added the files. I'm not sure what part of the stacktrace is interesting to you (although I guess it is only the first few calls).

[Unexpected RuntimeException_del.txt](https://github.com/webanno/webanno/files/188194/Unexpected.RuntimeException_del.txt)
[Unexpected RuntimeException_dont-know.txt](https://github.com/webanno/webanno/files/188195/Unexpected.RuntimeException_dont-know.txt)
[Unexpected RuntimeException_open_document.txt](https://github.com/webanno/webanno/files/188197/Unexpected.RuntimeException_open_document.txt)
[Unexpected RuntimeException_set_1.txt](https://github.com/webanno/webanno/files/188198/Unexpected.RuntimeException_set_1.txt)
[Unexpected RuntimeException_set_2.txt](https://github.com/webanno/webanno/files/188196/Unexpected.RuntimeException_set_2.txt)

**Comment by aakashysharma** [comment] 2016-04-03 22:47
Fixed along with #186

**Closed by aakashysharma** 2016-04-03 22:47 UTC
Labels: Annotation, bug
