### ISSUE TITLE
Curation: re-merging seems to delete the curation file

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#448] opened 2017-02-23 12:27 UTC
Using WebAnno -- 3.1.0-SNAPSHOT (2017-02-12 22:10:50, build 96280b8b14735b8574ef49310206d471eebfb2eb) with Chrome on Windows 8.1, I have/had a problem with four files of the "Sentiment DB" project:

15_09_05_d1441422303009_predictions_dataset_tokenized_16.tsv 
16_01_01_d1451624443950_predictions_dataset_tokenized_17.tsv 
15_11_01_d1446346842861_predictions_dataset_tokenized_23.tsv
16_02_01_d1454302841301_predictions_dataset_tokenized_22.tsv

First, the files "couldn't be loaded", after re-import into "Copy_of_Sentiment DB" the following occurred:
15_09_05_d1441422303009_predictions_dataset_tokenized_16.tsv seemed to be ok at first. I re-merged the file and it still worked. Then I tried to use "Go to"...and it went back to error messages. File 16_01_01_d1451624443950_predictions_dataset_tokenized_17.tsv couldn't be loaded. 15_11_01_d1446346842861_predictions_dataset_tokenized_23.tsv did load, but I didn't dare to re-merge. The funny thing with this one was that normally, at least one of the annotations is shown in the curation frame (the first annotator who clicked "Done"). In this file, none of the annotations was shown in the curation frame, although the overview on the left worked properly and distinguished between agreements and disagreements. I was able to finish the curation on this one. File 16_02_01_d1454302841301_predictions_dataset_tokenized_22.tsv, again, couldn't be loaded. I'll attach the respective error messages as screenshots.
![capture](https://cloud.githubusercontent.com/assets/13764947/23259111/c1855eca-f9cb-11e6-9f8f-a454f2f9549d.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13764947/23259122/c9b927f2-f9cb-11e6-8523-769c00837afa.PNG)

**Comment by sholschneider** [comment] 2017-02-24 13:35
Maybe re-merge isn't the source of the problem described above. One of the annotators just described the same problem for project Sentiment DB 2, using WebAnno -- 3.1.0-SNAPSHOT (2017-02-12 22:10:50, build 96280b8b14735b8574ef49310206d471eebfb2eb) with Chrome on Windows 8.1 and 7. The file can't be opened in annotation mode.
![capture](https://cloud.githubusercontent.com/assets/13764947/23305305/6607e6a2-fa9e-11e6-9db1-dcfb53bde6ec.PNG)

**Comment by reckart** [comment] 2017-02-24 14:35
Looks like your constraints file went missing - no idea how that could happen. Try deleting it from the UI and re-uploading it.

**Comment by sholschneider** [comment] 2017-02-24 14:43
Thanks! It worked for the annotation issue. However, it's weird that only two files has been affected.
![capture](https://cloud.githubusercontent.com/assets/13764947/23307454/e9ccb2ac-faa7-11e6-9595-8a80b78533fc.PNG)

**Comment by reckart** [comment] 2017-02-24 14:43
I have no idea why constraint files would go missing at all...

**Comment by reckart** [comment] 2017-08-11 20:19
Closing this since we have no idea how to reproduce this effect.

**Closed** 2017-08-11 20:19 UTC

**Comment by reckart** [comment] 2019-01-13 23:50
The cause of this problem was most likely #1164 which finally has been fixed now.
