### ISSUE TITLE
Monitoring: Switching between project does not work when agreement scores are computed beforehand

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#414] opened 2016-12-30 09:44 UTC
Once an agreement score is computed, it is not possible to switch directly to another project.
I am using WebAnno -- 3.0.0-beta-7 (2016-10-11 11:53:09, build 695d4c210728661f247e63ce5c4e0c37f8c93ae2) with Chrome on Windows 8.1.

**Comment by reckart** [comment] 2017-01-03 00:41
I have done this:

* log in
* go to the monitoring page
* select a project
* select a layer/feature for agreement calculation
* select another project

I couldn't notice any problem. Can you provide further details on how to reproduce your problem and what the problem actually is?

WebAnno -- 3.1.0-SNAPSHOT (2017-01-01 00:39:48, build f1c80caf8582bf9d84214c3e3f40d9387ddef01a

**Comment by reckart** [comment] 2017-08-11 20:12
Closing since no further information was provided. Assuming this is no longer an issue.

**Closed by reckart** 2017-08-11 20:12 UTC
Labels: bug, Monitoring
