### ISSUE TITLE
Curation: Sidebar on the left shows disagreement although there is none

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#320] opened 2016-08-07 09:54 UTC
Using WebAnno Testing (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155) with WIndows 8.1 on Chrome, the sidebar on the left sometimes shows disagreements during the curation process although there is none. Example: Sentiment DB/15_09_05_d1441422303009_predictions_dataset_tokenized_04.tsv, page 53.

**Comment by reckart** [comment] 2016-08-08 07:39
Seems to be a duplicate of #264.

**Comment by seyyaw** [comment] 2016-08-15 21:32
Yes, it seems a duplicate. Now sent 53 is not **red**

![image](https://cloud.githubusercontent.com/assets/1056051/17680467/816e9bd4-6340-11e6-91a1-52974b9fce68.png)

**Closed by seyyaw** 2016-08-15 21:32 UTC
Labels: bug, Curation
