### ISSUE TITLE
Curation mode update?

### ISSUE THREAD

**Issue by geraldinewalther** [webanno/webanno#472] opened 2017-03-15 16:06 UTC
Hi, 
I know this is a known issue, but is there any news on the bugs within the Curation mode in webanno 3.0/3.1? Might there be a fix in 3.2? It's such a useful feature. 
Thanks!

**Comment by reckart** [comment] 2017-03-15 19:56
Did you by any chance export/import the project for which curation mode is not working for you?

**Comment by reckart** [comment] 2017-03-15 19:57
Possibly a duplicate of https://github.com/webanno/webanno/issues/444

**Comment by reckart** [comment] 2017-03-16 06:45
Curation mode seems to load data quite a bit more often then necessary. This is something I have on the radar. I think in 3.2.0-SNAPSHOT, this has already improved a bit. On the other hand, if you use a SNAPSHOT or beta version, then WebAnno will by default activate data sanity checks which again slow down things (brave users may turn those checks off though).

**Comment by geraldinewalther** [comment] 2017-03-16 11:41
Thanks a lot. Yes, I noticed the redundant documents, too. I suppose, I'll try again with a more lively computer. The data is fairly sensitive, so I'd rather stick with stable versions for now. Thanks for your time and help!

**Comment by reckart** [comment] 2017-03-20 15:44
I found a couple of additional performance issues in the curation mode. Some of them will take a while to address, but I hope to gradually improve the performance as we go along...

**Comment by reckart** [comment] 2019-12-15 08:47
Curation mode is still slower than annotation mode because the diffs need to be calculated. but its performance has improved greatly since this issue was reported. Closing.

**Closed by reckart** 2019-12-15 08:47 UTC
Labels: Module: Curation, 🐛Bug
