### ISSUE TITLE
Link relation not shown if linked annotations are not on the same page

### ISSUE THREAD

**Issue by rs-unsilo** [webanno/webanno#1495] opened 2019-10-25 11:06 UTC
I have created a link feature between two layers. In the UI this is shown via red dotted line between two linked annotations. If the annotations are not on the same page the dotted line isn't shown at all.

This is not at huge deal since I can see the name of the destination annotation on the source annotation (but not the other way around though), but maybe a nice solution exists for this.

![Skærmbillede 2019-10-24 kl  15 11 11](https://user-images.githubusercontent.com/55238797/67566743-d40ec100-f728-11e9-9a4c-5791ec8c013c.png)

**Comment by reckart** [comment] 2019-10-25 18:44
Actually, this is a duplicate of https://github.com/webanno/webanno/issues/174

**Closed** 2019-11-10 10:14 UTC
Labels: 🎭Duplicate

**Comment by reckart** [comment] 2019-11-18 13:51
Btw. please feel free to "upvote" #174
