### ISSUE TITLE
Remote API returns wrong list of annotators for source document

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#324] opened 2016-08-23 10:33 UTC
When trying to get this list of annotators for a particular source document, it always returns the same single annotator name, no matter who the actual annotators are or if there are any at all.

Originally reported here: https://github.com/webanno/webanno/issues/312#issuecomment-241626444

**Comment by erikpetersonpb** [comment] 2016-08-26 21:44
This no longer returns the same single user for each document.  However, now it returns every possible user for every document, even if they haven't done any annotation on the source document.  Is that the expected behavior?  Also, how do I download the curated version of a document?

**Comment by reckart** [comment] 2016-08-26 22:06
@erikpetersonpb thanks for the feedback. It is not intended behavior. 

@anshul-tak The current code apparently doesn't check the state of the annotation document before returning it. The database may contain annotation document rows for all users even if no annotations have been made so far. We will have to check the state.

@erikpetersonpb When would you expect a user to be returned for a document? If the user has started working on the document or only if the user has marked the document as closed?

Regarding the curation document, I've opened a separate issue to look into this: https://github.com/webanno/webanno/issues/327

**Comment by erikpetersonpb** [comment] 2016-08-26 22:12
For me I think the most useful behavior is only to show if the user has marked the document as done.  Thanks.

**Comment by anshul-tak** [comment] 2016-08-28 10:53
@erikpetersonpb I have made changes, could you verify if it suffice the intended behavior.

**Comment by erikpetersonpb** [comment] 2016-08-29 02:15
It now only shows the annotators who have marked the document as done.  Thanks.  It's not showing the curation_user though, even if the document has been through curation and marked as done there ( checked in monitoring too).  How should that work?

**Comment by reckart** [comment] 2016-08-29 08:18
@erikpetersonpb @anshul-tak Hm, I need to have another look at how the curated document is stored internally. I had already feared that it might not appear because it's not managed through the database records in the same way as other annotation documents.

**Comment by reckart** [comment] 2016-08-29 08:22
@erikpetersonpb Anyway, let's continue the discussion on how to handle the curated data in a separate issue: https://github.com/webanno/webanno/issues/327

**Comment by erikpetersonpb** [comment] 2016-08-30 00:30
Listing source documents now includes the state of each document.  I think this would be useful for annotation documents also.  Rather than just returning users who have finished annotating (as I originally suggested) I think it would be useful to list users who have started or finished annotating the document, the associated state, and the timestamp.  So before it would return something like:

{'article_00959.pre.xmi': 'erik'}

With more info it would be:

{'article_00959.pre.xmi': [{'timestamp': '2016-08-22 16:39:54.0', 'state': 'FINISHED', 'user': u'erik'}]}
or potentially:

{'article_00963.pre.xmi': [{'timestamp': '2016-08-29 17:16:25.0', 'state': u'INPROGRESS', 'user': 'erik'}]}

Currently, the code in listAnnotationDocument is 

        if (hasAccess) {
            List<AnnotationDocument> annList = projectRepository
                    .listAllAnnotationDocuments(srcDocument);
            List<String> arrayAnnList = new ArrayList<String>();
            for (AnnotationDocument annDoc : annList) {
                if(annDoc.getState().equals(AnnotationDocumentState.FINISHED))
                    arrayAnnList.add(annDoc.getUser());                
                returnJSON.put(annDoc.getName(),arrayAnnList.isEmpty()?"":StringUtils.join(arrayAnnList, ','));
            }
        }


The following replacement that I've tried out would add information about the state and the time stamp and make it easier to access the annotator names:

        if (hasAccess) {
            List<AnnotationDocument> annList = projectRepository
                    .listAllAnnotationDocuments(srcDocument);
            JSONArray annotationDocumentJSONArr = new JSONArray();
            for (AnnotationDocument annDoc : annList) {
                JSONObject annotationDocumentJSONObj = new JSONObject();
                if (annDoc.getState() != AnnotationDocumentState.NEW) {
                    annotationDocumentJSONObj.put("user", annDoc.getUser());
                    annotationDocumentJSONObj.put("state", annDoc.getState());
                    annotationDocumentJSONObj.put("timestamp", annDoc.getTimestamp());
                    annotationDocumentJSONArr.put(annotationDocumentJSONObj);
                }
            }
            returnJSON.put(srcDocument.getName(),sourceDocumentJSONArr);
        }

Thank you.

**Closed** 2016-09-01 10:14 UTC
Labels: bug, Remote API

**Comment by reckart** [comment] 2016-10-04 20:22
@erikpetersonpb Is it actually necessary to display the list of users for a source document? How about instead returning one result per assigned user when listing the annotation documents for a source document, e.g.

```
[
  {
    "user":"richard", 
    "state":"NEW"
  },
  {
    "user":"anshul", 
    "state":"INPROGRESS",
    "timestamp":"2016-09-245T10:43:54+0200" 
  },
  {
    "user":"abc",
    "state":"COMPLETE",
    "timestamp":"2016-09-245T10:46:28+0200"
  }
]
```
