### ISSUE TITLE
Error message "Relation does not have its source feature (Governor) set: Dependency"

### ISSUE THREAD

**Issue by thomaskrause** [webanno/webanno#1032] opened 2018-08-06 13:19 UTC
When exporting one of our corpora to WebAnno TSV3 we get an exception:

```
Caused by: java.lang.IllegalStateException: Relation does not have its source feature (Governor) set: Dependency
   sofa: _InitialView
   begin: 1508
   end: 1515
   Governor: <null>
   Dependent: Token
      sofa: _InitialView
      begin: 1508
      end: 1515
      parent: <null>
      lemma: Lemma
         sofa: _InitialView
         begin: 1508
         end: 1515
         value: "letzt"
      stem: <null>
      pos: POS
         sofa: _InitialView
         begin: 1508
         end: 1515
         PosValue: "ADJA"
         coarseValue: <null>
      morph: <null>
   DependencyType: "ATTR"
   flavor: "basic"

	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XCasDocumentBuilder.scanUnitForActiveColumns(Tsv3XCasDocumentBuilder.java:277) ~[webanno-io-tsv-3.5.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XCasDocumentBuilder.of(Tsv3XCasDocumentBuilder.java:223) ~[webanno-io-tsv-3.5.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3XWriter.process(WebannoTsv3XWriter.java:56) ~[webanno-io-tsv-3.5.0-SNAPSHOT.jar:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.2.jar:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.2.jar:2.10.2]
	... 39 more
```

The corpus was originally annotated with an older version of WebAnno, but we get this error after migrating to thelatest release (WebAnno 3.4.5) and 3.5.0-SNAPSHOT version, too.

I attached a ZIP of the project-subfolder for the problematic document:
[relation_error_project.zip](https://github.com/webanno/webanno/files/2262663/relation_error_project.zip)

**Comment by reckart** [comment] 2018-08-07 11:46
@thomaskrause Did you run the CAS Doctor over the project?

**Comment by reckart** [comment] 2018-08-07 11:48
@thomaskrause If I remember correctly, the problem usually occurs in older WebAnno versions when one of the POS tags to which the dependency relation connects on screen is deleted.

**Comment by reckart** [comment] 2018-09-24 16:59
@thomaskrause The ZIP archive that you provided only contains plain-text and serialized CAS files. It is quite tedious to reconstruct a suitable project configuration from a serialized CAS file in order to reproduce your problem. 

Would it be possible to provide a project export? 

To construct a project with only a single document, then export the project using any format that works (can be "plain text" - it does not matter), then re-import the project, delete all the documents except the ones required to reproduce the issue, then export the project again in any format that works (can again be "plain text" - it does not matter).

**Comment by reckart** [comment] 2021-01-12 21:25
Closing since there was no further input.

**Closed by reckart** 2021-01-12 21:25 UTC
Labels: 🐛Bug
