### ISSUE TITLE
Switching between documents during curation resets settings

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#321] opened 2016-08-12 08:59 UTC
When switching between documents during curation, the setting options change to their initial state (e.g.: number of sentences).
I am using WebAnno Testing 3.0.0-SNAPSHOT (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155) with Chrome on Windows 8.1.

**Comment by reckart** [comment] 2017-03-28 21:15
Sounds like a duplicate of #468 "Number of visible sentences not correctly applied when opening/switching documents".

**Closed by reckart** 2017-03-28 21:15 UTC
Labels: bug, Curation
