### ISSUE TITLE
Project export does not work

### ISSUE THREAD

**Issue by AsadMehmoodappen** [webanno/webanno#382] opened 2016-10-12 04:57 UTC
Hi,

We have been having issues with project export. Everytime we try to export the project, user interface dies and export stays at 0% and eventually we have to reboot the server to fix this issue.
![webanno](https://cloud.githubusercontent.com/assets/22313951/19297864/6c94867a-9094-11e6-9e56-96d7fe371b24.png)

**Comment by reckart** [comment] 2016-10-12 06:10
Unfortunately, you cut the version information from the bottom of the screenshot, so I cannot tell which version you are using.

Assuming you are using WebAnno 2.x, try setting the export format from "AUTO" to "UIMA Binary CAS". Most likely, there is some annotation structure that the automatically chosen writer does not support causing it to throw an exception.

**Comment by reckart** [comment] 2016-10-12 06:21
Sounds like a duplicate of #100.

**Comment by AsadMehmoodappen** [comment] 2016-10-14 05:48
Hi,

Thank you very much for your feedback.

I will try that and will update this issue ticket.

Asad

**Comment by reckart** [comment] 2017-01-25 14:27
Closing this issue as user has not responded in several weeks.

**Closed by reckart** 2017-01-25 14:27 UTC
Labels: support-request
